#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
# author    : "Manuel Verde EA7TB"
# credits   : "Manuel EA7TB www.ea7tb.com"
# copyright : "Copyright 2022, www.ea7tb.com"

"""
Controlando GPIO con Python
"""

import os
import sys

from time import sleep
from pyA20.gpio import gpio
from pyA20.gpio import port

rele = port.PA12
#led1 = port.PA11
#led2 = port.PA6

gpio.init()
gpio.setcfg(rele, gpio.OUTPUT)
#gpio.setcfg(led0, gpio.OUTPUT)
#gpio.setcfg(led1, gpio.OUTPUT)
#gpio.setcfg(led2, gpio.OUTPUT)

try:
    print ("Pulsa CTRL+C para salir")
    while True:
          gpio.output(rele, 1)
          print ("puerto arriba")
          #sleep(0.5)

          sleep(3.2)
          gpio.output(rele,0)
          print("Puero Abajo")
          sleep(3.2)

except KeyboardInterrupt:
    print ("Saliendo")

           [ line 42/42 (100%), col 1/1 (100%),
